package com.thecrazy8.kubejseditor;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class CreateFillingEditorScreen extends Screen {
    private final Screen parent;
    private EditBox outputItemBox;
    private EditBox inputItemBox;
    private EditBox fluidBox;
    
    public CreateFillingEditorScreen(Screen parent) {
        super(Component.literal("Create: Filling Recipe Editor"));
        this.parent = parent;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int leftMargin = 20;
        int topMargin = 60;
        int fieldWidth = this.width - 40;
        int fieldHeight = 20;
        int spacing = 30;
        
        // Output Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Output Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin, 100, fieldHeight).build()).active = false;
        
        outputItemBox = new EditBox(this.font, leftMargin + 110, topMargin, fieldWidth - 110, fieldHeight, Component.literal("Output Item"));
        outputItemBox.setHint(Component.literal("e.g., create:blaze_cake"));
        this.addRenderableWidget(outputItemBox);
        
        // Input Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Input Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing, 100, fieldHeight).build()).active = false;
        
        inputItemBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing, fieldWidth - 110, fieldHeight, Component.literal("Input Item"));
        inputItemBox.setHint(Component.literal("e.g., create:blaze_cake_base"));
        this.addRenderableWidget(inputItemBox);
        
        // Fluid
        this.addRenderableWidget(Button.builder(
            Component.literal("Fluid:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 2, 100, fieldHeight).build()).active = false;
        
        fluidBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 2, fieldWidth - 110, fieldHeight, Component.literal("Fluid"));
        fluidBox.setHint(Component.literal("Format: fluid_id,amount (e.g., minecraft:lava,250)"));
        this.addRenderableWidget(fluidBox);
        
        // Save button
        this.addRenderableWidget(Button.builder(
            Component.literal("Generate & Download Script"),
            button -> generateAndDownloadScript()
        ).bounds(this.width / 2 - 100, this.height - 50, 200, 20).build());
        
        // Back button
        this.addRenderableWidget(Button.builder(
            Component.literal("Back"),
            button -> this.minecraft.setScreen(parent)
        ).bounds(this.width / 2 - 100, this.height - 28, 200, 20).build());
    }
    
    private void generateAndDownloadScript() {
        try {
            String outputItem = outputItemBox.getValue().trim();
            String inputItem = inputItemBox.getValue().trim();
            String fluid = fluidBox.getValue().trim();
            
            if (outputItem.isEmpty() || inputItem.isEmpty() || fluid.isEmpty()) {
                return;
            }
            
            String[] fluidParts = fluid.split(",");
            if (fluidParts.length != 2) {
                return;
            }
            
            StringBuilder script = new StringBuilder();
            script.append("// Create: Filling Recipe\n");
            script.append("// Generated by KubeJS GUI Editor\n\n");
            script.append("ServerEvents.recipes(event => {\n");
            script.append("    event.recipes.createFilling('").append(outputItem).append("', [\n");
            script.append("        '").append(inputItem).append("',\n");
            script.append("        Fluid.of('").append(fluidParts[0].trim()).append("', ")
                  .append(fluidParts[1].trim()).append(")\n");
            script.append("    ]);\n");
            script.append("});\n");
            
            File minecraftDir = this.minecraft.gameDirectory;
            File kubejsDir = new File(minecraftDir, "kubejs/server_scripts");
            kubejsDir.mkdirs();
            
            File scriptFile = new File(kubejsDir, "create_filling_custom.js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script.toString());
            }
            
            this.minecraft.player.sendSystemMessage(Component.literal("§aScript saved to: " + scriptFile.getAbsolutePath()));
            
        } catch (IOException e) {
            this.minecraft.player.sendSystemMessage(Component.literal("§cError saving script: " + e.getMessage()));
        }
    }
    
    @Override
    public void render(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(guiGraphics, mouseX, mouseY, partialTick);
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        guiGraphics.drawCenteredString(this.font, this.title, this.width / 2, 15, 0xFFFFFF);
        
        guiGraphics.drawString(this.font, "Fills an item with a fluid (e.g., blaze cake)", 20, this.height - 65, 0xAAAAAA);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
