package com.thecrazy8.kubejseditor;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class FDCuttingBoardEditorScreen extends Screen {
    private final Screen parent;
    private EditBox outputsBox;
    private EditBox inputItemBox;
    private EditBox toolBox;
    
    public FDCuttingBoardEditorScreen(Screen parent) {
        super(Component.literal("Farmer's Delight: Cutting Board Editor"));
        this.parent = parent;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int leftMargin = 20;
        int topMargin = 60;
        int fieldWidth = this.width - 40;
        int fieldHeight = 20;
        int spacing = 30;
        
        // Input Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Input Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin, 100, fieldHeight).build()).active = false;
        
        inputItemBox = new EditBox(this.font, leftMargin + 110, topMargin, fieldWidth - 110, fieldHeight, Component.literal("Input Item"));
        inputItemBox.setHint(Component.literal("e.g., minecraft:pumpkin"));
        this.addRenderableWidget(inputItemBox);
        
        // Outputs
        this.addRenderableWidget(Button.builder(
            Component.literal("Outputs:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing, 100, fieldHeight).build()).active = false;
        
        outputsBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing, fieldWidth - 110, fieldHeight * 2, Component.literal("Outputs"));
        outputsBox.setHint(Component.literal("One per line:\nminecraft:pumpkin_seeds\n4x minecraft:pumpkin_slice"));
        this.addRenderableWidget(outputsBox);
        
        // Tool
        this.addRenderableWidget(Button.builder(
            Component.literal("Tool:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 3, 100, fieldHeight).build()).active = false;
        
        toolBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 3, fieldWidth - 110, fieldHeight, Component.literal("Tool"));
        toolBox.setHint(Component.literal("e.g., farmersdelight:knife or #forge:tools/knives"));
        this.addRenderableWidget(toolBox);
        
        // Save button
        this.addRenderableWidget(Button.builder(
            Component.literal("Generate & Download Script"),
            button -> generateAndDownloadScript()
        ).bounds(this.width / 2 - 100, this.height - 50, 200, 20).build());
        
        // Back button
        this.addRenderableWidget(Button.builder(
            Component.literal("Back"),
            button -> this.minecraft.setScreen(parent)
        ).bounds(this.width / 2 - 100, this.height - 28, 200, 20).build());
    }
    
    private void generateAndDownloadScript() {
        try {
            String inputItem = inputItemBox.getValue().trim();
            String outputs = outputsBox.getValue().trim();
            String tool = toolBox.getValue().trim();
            
            if (inputItem.isEmpty() || outputs.isEmpty() || tool.isEmpty()) {
                return;
            }
            
            StringBuilder script = new StringBuilder();
            script.append("// Farmer's Delight: Cutting Board Recipe\n");
            script.append("// Generated by KubeJS GUI Editor\n\n");
            script.append("ServerEvents.recipes(event => {\n");
            script.append("    event.recipes.farmersdelight.cutting(\n");
            script.append("        [\n");
            
            String[] items = outputs.split("\n");
            for (int i = 0; i < items.length; i++) {
                String item = items[i].trim();
                if (!item.isEmpty()) {
                    script.append("            Item.of('").append(item).append("')");
                    if (i < items.length - 1) script.append(",");
                    script.append("\n");
                }
            }
            
            script.append("        ],\n");
            script.append("        '").append(inputItem).append("',\n");
            script.append("        '").append(tool).append("'\n");
            script.append("    );\n");
            script.append("});\n");
            
            File minecraftDir = this.minecraft.gameDirectory;
            File kubejsDir = new File(minecraftDir, "kubejs/server_scripts");
            kubejsDir.mkdirs();
            
            File scriptFile = new File(kubejsDir, "farmersdelight_cutting_board_custom.js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script.toString());
            }
            
            this.minecraft.player.sendSystemMessage(Component.literal("§aScript saved to: " + scriptFile.getAbsolutePath()));
            
        } catch (IOException e) {
            this.minecraft.player.sendSystemMessage(Component.literal("§cError saving script: " + e.getMessage()));
        }
    }
    
    @Override
    public void render(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(guiGraphics, mouseX, mouseY, partialTick);
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        guiGraphics.drawCenteredString(this.font, this.title, this.width / 2, 15, 0xFFFFFF);
        
        guiGraphics.drawString(this.font, "Use # for tags (e.g., #forge:tools/knives)", 20, this.height - 65, 0xAAAAAA);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
