package com.thecrazy8.kubejseditor;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class ShapelessCraftingEditorScreen extends Screen {
    private final Screen parent;
    private EditBox outputItemBox;
    private EditBox outputCountBox;
    private EditBox ingredientsBox;
    
    public ShapelessCraftingEditorScreen(Screen parent) {
        super(Component.literal("Shapeless Crafting Recipe Editor"));
        this.parent = parent;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int leftMargin = 20;
        int topMargin = 60;
        int fieldWidth = this.width - 40;
        int fieldHeight = 20;
        int spacing = 30;
        
        // Output Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Output Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin, 100, fieldHeight).build()).active = false;
        
        outputItemBox = new EditBox(this.font, leftMargin + 110, topMargin, fieldWidth - 110, fieldHeight, Component.literal("Output Item"));
        outputItemBox.setHint(Component.literal("e.g., minecraft:iron_ingot"));
        this.addRenderableWidget(outputItemBox);
        
        // Output Count
        this.addRenderableWidget(Button.builder(
            Component.literal("Count:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing, 100, fieldHeight).build()).active = false;
        
        outputCountBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing, fieldWidth - 110, fieldHeight, Component.literal("Output Count"));
        outputCountBox.setHint(Component.literal("e.g., 9"));
        outputCountBox.setValue("1");
        this.addRenderableWidget(outputCountBox);
        
        // Ingredients
        this.addRenderableWidget(Button.builder(
            Component.literal("Ingredients:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 2, 100, fieldHeight).build()).active = false;
        
        ingredientsBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 2, fieldWidth - 110, fieldHeight * 3, Component.literal("Ingredients"));
        ingredientsBox.setHint(Component.literal("One item per line, e.g.:\nminecraft:iron_block\nminecraft:stick"));
        this.addRenderableWidget(ingredientsBox);
        
        // Save button
        this.addRenderableWidget(Button.builder(
            Component.literal("Generate & Download Script"),
            button -> generateAndDownloadScript()
        ).bounds(this.width / 2 - 100, this.height - 50, 200, 20).build());
        
        // Back button
        this.addRenderableWidget(Button.builder(
            Component.literal("Back"),
            button -> this.minecraft.setScreen(parent)
        ).bounds(this.width / 2 - 100, this.height - 28, 200, 20).build());
    }
    
    private void generateAndDownloadScript() {
        try {
            String outputItem = outputItemBox.getValue().trim();
            String outputCount = outputCountBox.getValue().trim();
            String ingredients = ingredientsBox.getValue().trim();
            
            if (outputItem.isEmpty() || ingredients.isEmpty()) {
                return;
            }
            
            StringBuilder script = new StringBuilder();
            script.append("// Shapeless Crafting Recipe\n");
            script.append("// Generated by KubeJS GUI Editor\n\n");
            script.append("ServerEvents.recipes(event => {\n");
            script.append("    event.shapeless(\n");
            script.append("        '").append(outputCount.isEmpty() ? "1" : outputCount)
                  .append("x ").append(outputItem).append("',\n");
            script.append("        [\n");
            
            String[] items = ingredients.split("\n");
            for (int i = 0; i < items.length; i++) {
                String item = items[i].trim();
                if (!item.isEmpty()) {
                    script.append("            '").append(item).append("'");
                    if (i < items.length - 1) script.append(",");
                    script.append("\n");
                }
            }
            script.append("        ]\n");
            script.append("    );\n");
            script.append("});\n");
            
            File minecraftDir = this.minecraft.gameDirectory;
            File kubejsDir = new File(minecraftDir, "kubejs/server_scripts");
            kubejsDir.mkdirs();
            
            File scriptFile = new File(kubejsDir, "shapeless_crafting_custom.js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script.toString());
            }
            
            this.minecraft.player.sendSystemMessage(Component.literal("§aScript saved to: " + scriptFile.getAbsolutePath()));
            
        } catch (IOException e) {
            this.minecraft.player.sendSystemMessage(Component.literal("§cError saving script: " + e.getMessage()));
        }
    }
    
    @Override
    public void render(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(guiGraphics, mouseX, mouseY, partialTick);
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        guiGraphics.drawCenteredString(this.font, this.title, this.width / 2, 15, 0xFFFFFF);
        
        guiGraphics.drawString(this.font, "Add one ingredient per line", 20, this.height - 65, 0xAAAAAA);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
