package com.thecrazy8.kubejseditor;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class ShapedCraftingEditorScreen extends Screen {
    private final Screen parent;
    private EditBox outputItemBox;
    private EditBox outputCountBox;
    private EditBox patternBox;
    private EditBox keysBox;
    
    public ShapedCraftingEditorScreen(Screen parent) {
        super(Component.literal("Shaped Crafting Recipe Editor"));
        this.parent = parent;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int leftMargin = 20;
        int topMargin = 40;
        int fieldWidth = this.width - 40;
        int fieldHeight = 20;
        int spacing = 30;
        
        // Output Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Output Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin, 100, fieldHeight).build()).active = false;
        
        outputItemBox = new EditBox(this.font, leftMargin + 110, topMargin, fieldWidth - 110, fieldHeight, Component.literal("Output Item"));
        outputItemBox.setHint(Component.literal("e.g., minecraft:diamond_sword"));
        this.addRenderableWidget(outputItemBox);
        
        // Output Count
        this.addRenderableWidget(Button.builder(
            Component.literal("Count:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing, 100, fieldHeight).build()).active = false;
        
        outputCountBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing, fieldWidth - 110, fieldHeight, Component.literal("Output Count"));
        outputCountBox.setHint(Component.literal("e.g., 1"));
        outputCountBox.setValue("1");
        this.addRenderableWidget(outputCountBox);
        
        // Pattern
        this.addRenderableWidget(Button.builder(
            Component.literal("Pattern:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 2, 100, fieldHeight).build()).active = false;
        
        patternBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 2, fieldWidth - 110, fieldHeight * 2, Component.literal("Pattern"));
        patternBox.setHint(Component.literal("3 lines: AAA / ABA / AAA (use space for empty)"));
        this.addRenderableWidget(patternBox);
        
        // Keys
        this.addRenderableWidget(Button.builder(
            Component.literal("Keys:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 4, 100, fieldHeight).build()).active = false;
        
        keysBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 4, fieldWidth - 110, fieldHeight * 2, Component.literal("Keys"));
        keysBox.setHint(Component.literal("Format: A=minecraft:stick,B=minecraft:diamond (comma-separated)"));
        this.addRenderableWidget(keysBox);
        
        // Save button
        this.addRenderableWidget(Button.builder(
            Component.literal("Generate & Download Script"),
            button -> generateAndDownloadScript()
        ).bounds(this.width / 2 - 100, this.height - 50, 200, 20).build());
        
        // Back button
        this.addRenderableWidget(Button.builder(
            Component.literal("Back"),
            button -> this.minecraft.setScreen(parent)
        ).bounds(this.width / 2 - 100, this.height - 28, 200, 20).build());
    }
    
    private void generateAndDownloadScript() {
        try {
            String outputItem = outputItemBox.getValue().trim();
            String outputCount = outputCountBox.getValue().trim();
            String pattern = patternBox.getValue().trim();
            String keys = keysBox.getValue().trim();
            
            if (outputItem.isEmpty() || pattern.isEmpty() || keys.isEmpty()) {
                return;
            }
            
            StringBuilder script = new StringBuilder();
            script.append("// Shaped Crafting Recipe\n");
            script.append("// Generated by KubeJS GUI Editor\n\n");
            script.append("ServerEvents.recipes(event => {\n");
            script.append("    event.shaped(\n");
            script.append("        '").append(outputCount.isEmpty() ? "1" : outputCount)
                  .append("x ").append(outputItem).append("',\n");
            script.append("        [\n");
            
            String[] lines = pattern.split("\n");
            for (int i = 0; i < lines.length && i < 3; i++) {
                script.append("            '").append(lines[i].trim()).append("'");
                if (i < Math.min(lines.length, 3) - 1) script.append(",");
                script.append("\n");
            }
            script.append("        ],\n");
            script.append("        {\n");
            
            String[] keyPairs = keys.split(",");
            for (int i = 0; i < keyPairs.length; i++) {
                String[] pair = keyPairs[i].split("=");
                if (pair.length == 2) {
                    script.append("            ").append(pair[0].trim()).append(": '")
                          .append(pair[1].trim()).append("'");
                    if (i < keyPairs.length - 1) script.append(",");
                    script.append("\n");
                }
            }
            script.append("        }\n");
            script.append("    );\n");
            script.append("});\n");
            
            File minecraftDir = this.minecraft.gameDirectory;
            File kubejsDir = new File(minecraftDir, "kubejs/server_scripts");
            kubejsDir.mkdirs();
            
            File scriptFile = new File(kubejsDir, "shaped_crafting_custom.js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script.toString());
            }
            
            this.minecraft.player.sendSystemMessage(Component.literal("§aScript saved to: " + scriptFile.getAbsolutePath()));
            
        } catch (IOException e) {
            this.minecraft.player.sendSystemMessage(Component.literal("§cError saving script: " + e.getMessage()));
        }
    }
    
    @Override
    public void render(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(guiGraphics, mouseX, mouseY, partialTick);
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        guiGraphics.drawCenteredString(this.font, this.title, this.width / 2, 15, 0xFFFFFF);
        
        guiGraphics.drawString(this.font, "Pattern: Use 3 lines, 3 chars each (AAA / ABA / AAA)", 20, this.height - 75, 0xAAAAAA);
        guiGraphics.drawString(this.font, "Keys: A=minecraft:stick,B=minecraft:diamond", 20, this.height - 65, 0xAAAAAA);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
