package com.thecrazy8.kubejseditor;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class SmithingEditorScreen extends Screen {
    private final Screen parent;
    private EditBox baseItemBox;
    private EditBox additionItemBox;
    private EditBox templateItemBox;
    private EditBox outputItemBox;
    
    public SmithingEditorScreen(Screen parent) {
        super(Component.literal("Smithing Recipe Editor"));
        this.parent = parent;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int leftMargin = 20;
        int topMargin = 60;
        int fieldWidth = this.width - 40;
        int fieldHeight = 20;
        int spacing = 30;
        
        // Template Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Template:"),
            button -> {}
        ).bounds(leftMargin, topMargin, 100, fieldHeight).build()).active = false;
        
        templateItemBox = new EditBox(this.font, leftMargin + 110, topMargin, fieldWidth - 110, fieldHeight, Component.literal("Template Item"));
        templateItemBox.setHint(Component.literal("e.g., minecraft:netherite_upgrade_smithing_template"));
        this.addRenderableWidget(templateItemBox);
        
        // Base Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Base Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing, 100, fieldHeight).build()).active = false;
        
        baseItemBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing, fieldWidth - 110, fieldHeight, Component.literal("Base Item"));
        baseItemBox.setHint(Component.literal("e.g., minecraft:diamond_sword"));
        this.addRenderableWidget(baseItemBox);
        
        // Addition Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Addition:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 2, 100, fieldHeight).build()).active = false;
        
        additionItemBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 2, fieldWidth - 110, fieldHeight, Component.literal("Addition Item"));
        additionItemBox.setHint(Component.literal("e.g., minecraft:netherite_ingot"));
        this.addRenderableWidget(additionItemBox);
        
        // Output Item
        this.addRenderableWidget(Button.builder(
            Component.literal("Output Item:"),
            button -> {}
        ).bounds(leftMargin, topMargin + spacing * 3, 100, fieldHeight).build()).active = false;
        
        outputItemBox = new EditBox(this.font, leftMargin + 110, topMargin + spacing * 3, fieldWidth - 110, fieldHeight, Component.literal("Output Item"));
        outputItemBox.setHint(Component.literal("e.g., minecraft:netherite_sword"));
        this.addRenderableWidget(outputItemBox);
        
        // Save button
        this.addRenderableWidget(Button.builder(
            Component.literal("Generate & Download Script"),
            button -> generateAndDownloadScript()
        ).bounds(this.width / 2 - 100, this.height - 50, 200, 20).build());
        
        // Back button
        this.addRenderableWidget(Button.builder(
            Component.literal("Back"),
            button -> this.minecraft.setScreen(parent)
        ).bounds(this.width / 2 - 100, this.height - 28, 200, 20).build());
    }
    
    private void generateAndDownloadScript() {
        try {
            String template = templateItemBox.getValue().trim();
            String base = baseItemBox.getValue().trim();
            String addition = additionItemBox.getValue().trim();
            String output = outputItemBox.getValue().trim();
            
            if (template.isEmpty() || base.isEmpty() || addition.isEmpty() || output.isEmpty()) {
                return;
            }
            
            StringBuilder script = new StringBuilder();
            script.append("// Smithing Recipe\n");
            script.append("// Generated by KubeJS GUI Editor\n\n");
            script.append("ServerEvents.recipes(event => {\n");
            script.append("    event.smithing(\n");
            script.append("        '").append(output).append("',\n");
            script.append("        '").append(base).append("',\n");
            script.append("        '").append(addition).append("',\n");
            script.append("        '").append(template).append("'\n");
            script.append("    );\n");
            script.append("});\n");
            
            File minecraftDir = this.minecraft.gameDirectory;
            File kubejsDir = new File(minecraftDir, "kubejs/server_scripts");
            kubejsDir.mkdirs();
            
            File scriptFile = new File(kubejsDir, "smithing_custom.js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script.toString());
            }
            
            this.minecraft.player.sendSystemMessage(Component.literal("§aScript saved to: " + scriptFile.getAbsolutePath()));
            
        } catch (IOException e) {
            this.minecraft.player.sendSystemMessage(Component.literal("§cError saving script: " + e.getMessage()));
        }
    }
    
    @Override
    public void render(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(guiGraphics, mouseX, mouseY, partialTick);
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        guiGraphics.drawCenteredString(this.font, this.title, this.width / 2, 15, 0xFFFFFF);
        
        guiGraphics.drawString(this.font, "Smithing Table recipes (1.20+ format)", 20, this.height - 65, 0xAAAAAA);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
